name: HMG Pipeline

on:
  push:
    branches-ignore: [ main ]

jobs:
  quality-security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: .
          args: >
            -Dsonar.organization=alportech
            -Dsonar.projectKey=viniciusalves23_DeployHeroku

      - name: Run Trivy Security Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL,HIGH'

  deploy-hmg:
    needs: quality-security
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # 1. Instala o CLI oficial do Heroku
      - name: Install Heroku CLI
        run: curl https://cli-assets.heroku.com/install.sh | sh

      # 2. Faz o login no Registry de Containers do Heroku
      - name: Login to Heroku Container Registry
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:login

      # 3. Faz o Build e Push da imagem Docker
      - name: Build and Push Docker Image
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:push web --app vini-app-hmg

      # 4. Libera a versão (Release) para entrar no ar
      - name: Release Docker Image
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:release web --app vini-app-hmg