name: PROD Pipeline (CD)

on:
  push:
    branches: [ main ] # Dispara após o merge do PR na main

jobs:
  quality-security:
    name: Quality and Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Necessário para uma análise precisa do SonarCloud

      # 1. Análise de Qualidade com SonarCloud na Main
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: .
          args: >
            -Dsonar.organization=alportech
            -Dsonar.projectKey=viniciusalves23_DeployHeroku

      # 2. Análise de Segurança de Dependências com Trivy
      - name: Run Trivy Security Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          format: 'table'
          exit-code: '1' # Trava o deploy de PROD se houver risco crítico
          severity: 'CRITICAL,HIGH'

  deploy-prod:
    name: Deploy to Heroku PROD
    needs: quality-security # Só avança para produção se os testes passarem
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # 3. Instala o CLI oficial do Heroku (Jeito Sênior, fugindo do bug da action)
      - name: Install Heroku CLI
        run: curl https://cli-assets.heroku.com/install.sh | sh

      # 4. Faz o login no Registry de Containers do Heroku
      - name: Login to Heroku Container Registry
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:login

      # 5. Faz o Build e Push da imagem Docker para Produção
      - name: Build and Push Docker Image
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:push web --app vini-app-prod

      # 6. Libera a versão (Release) para entrar no ar
      - name: Release Docker Image
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:release web --app vini-app-prod